<?php
session_start();
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Security check
if (!isset($_SESSION['teacher_id']) || empty($_SESSION['teacher_id'])) {
    header("Location: logginn.php");
    exit;
}

// Database configuration
$host = "aws-1-eu-north-1.pooler.supabase.com";
$port = "6543";
$dbname = "postgres";
$user = "postgres.mqtuzltstbshtjigzujz";
$password = "Ernestbizz..123";

// Database connection
try {
    $pdo = new PDO("pgsql:host=$host;port=$port;dbname=$dbname", $user, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false
    ]);
} catch (PDOException $e) {
    error_log("Database connection failed: " . $e->getMessage());
    die("Connection failed. Please try again later.");
}

// Sanitization
function sanitize($data) {
    if (is_array($data)) return array_map('sanitize', $data);
    return htmlspecialchars(trim($data), ENT_QUOTES, 'UTF-8');
}

// Validate request
if (!isset($_POST['note_id']) || !is_numeric($_POST['note_id'])) {
    die("Invalid request: Lesson note ID is required.");
}
$note_id = (int)$_POST['note_id'];
$teacher_id = $_SESSION['teacher_id'];

// Fetch lesson note
try {
    $stmt = $pdo->prepare("SELECT * FROM lesson_notes WHERE id = ? AND teacher_id = ?");
    $stmt->execute([$note_id, $teacher_id]);
    $note = $stmt->fetch();
    if (!$note) die("Lesson note not found or access denied.");
} catch (PDOException $e) {
    error_log("Database query failed: " . $e->getMessage());
    die("Error retrieving lesson note. Please try again.");
}

// Include FPDF
require('fpdf.php');

class PDF extends FPDF {
    private $primaryColor = [33, 37, 41];
    private $accentColor = [52, 58, 64];
    private $darkColor = [23, 32, 42];
    private $borderColor = [200, 200, 200];
    private $textColor = [33, 37, 41];
    private $mutedColor = [108, 117, 125];

    // Header
    function Header() {
        if ($this->PageNo() == 1) {
            $this->SetFont('Arial', 'B', 20);
            $this->SetTextColor(0, 0, 0);
            $this->Cell(0, 12, 'LESSON PLAN', 0, 1, 'C');

            $this->SetFont('Arial', 'I', 11);
            $this->Cell(0, 6, 'Professional Teaching Resource Document', 0, 1, 'C');

            // Accent line
            $this->SetFillColor($this->accentColor[0], $this->accentColor[1], $this->accentColor[2]);
            $this->Rect(10, 30, 190, 2, 'F');
            $this->Ln(12);
        }
    }

    // Footer
    function Footer() {
        $this->SetY(-20);
        $this->SetFont('Arial', 'I', 9);
        $this->SetTextColor($this->mutedColor[0], $this->mutedColor[1], $this->mutedColor[2]);
        $this->SetDrawColor($this->borderColor[0], $this->borderColor[1], $this->borderColor[2]);
        $this->Line(10, $this->GetY(), 200, $this->GetY());
        $this->Ln(3);
        $this->Cell(0, 10, 'Generated by LessonNotes Pro AI - Page ' . $this->PageNo(), 0, 0, 'C');
    }

    function SectionTitle($title) {
        $this->SetFont('Arial', 'B', 14);
        $this->SetTextColor($this->primaryColor[0], $this->primaryColor[1], $this->primaryColor[2]);
        $this->Cell(0, 10, $title, 0, 1, 'L');
        $this->Ln(3);
    }

    function ColoredCell($w, $h, $txt, $border, $ln, $align, $fill) {
        $this->SetTextColor($this->darkColor[0], $this->darkColor[1], $this->darkColor[2]);
        $this->SetFont('Arial', 'B', 11);
        $this->SetDrawColor($this->borderColor[0], $this->borderColor[1], $this->borderColor[2]);
        $this->Cell($w, $h, $txt, $border, $ln, $align, $fill);
    }

    function ContentCell($w, $h, $txt, $border, $ln, $align) {
        $this->SetTextColor($this->textColor[0], $this->textColor[1], $this->textColor[2]);
        $this->SetFont('Arial', '', 11);
        $this->SetDrawColor($this->borderColor[0], $this->borderColor[1], $this->borderColor[2]);
        $this->Cell($w, $h, $txt, $border, $ln, $align);
    }

    function PhaseBox($phaseNum, $content) {
        $phaseTitles = [1 => '(Starter)', 2 => '(Main)', 3 => '(Reflection)'];
        $titleText = "PHASE $phaseNum " . ($phaseTitles[$phaseNum] ?? "");
        $this->SetTextColor($this->textColor[0], $this->textColor[1], $this->textColor[2]);
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 8, $titleText, 1, 1, 'L');

        $this->SetFont('Arial', '', 11);
        $this->SetDrawColor($this->borderColor[0], $this->borderColor[1], $this->borderColor[2]);

        if (empty(trim($content))) {
            $content = "No content provided for this phase.";
            $this->SetTextColor($this->mutedColor[0], $this->mutedColor[1], $this->mutedColor[2]);
            $this->SetFont('Arial', 'I', 11);
        }

        $this->MultiCell(0, 8, $content, 1, 'L');
        $this->Ln(4);
    }

    function SafeMultiCell($w, $h, $txt, $border = 0, $align = 'J') {
        $txt = mb_convert_encoding($txt, 'ISO-8859-1', 'UTF-8');
        $this->MultiCell($w, $h, $txt, $border, $align);
    }

    // Getters
    public function getBorderColor() { return $this->borderColor; }
    public function getDarkColor() { return $this->darkColor; }
    public function getMutedColor() { return $this->mutedColor; }
    public function getPrimaryColor() { return $this->primaryColor; }
    public function getTextColor() { return $this->textColor; }
}

// Create PDF
$pdf = new PDF();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 25);
$sanitizedNote = sanitize($note);

// --- BASIC INFORMATION ---
$pdf->SectionTitle('Basic Information');
$borderColor = $pdf->getBorderColor();
$pdf->SetDrawColor($borderColor[0], $borderColor[1], $borderColor[2]);

$pdf->ColoredCell(47, 10, 'Subject:', 1, 0, 'L', false);
$pdf->ContentCell(47, 10, $sanitizedNote['subject'], 1, 0, 'L');
$pdf->ColoredCell(48, 10, 'Class Size:', 1, 0, 'L', false);
$pdf->ContentCell(48, 10, $sanitizedNote['class_size'], 1, 1, 'L');

$pdf->ColoredCell(47, 10, 'Week Ending:', 1, 0, 'L', false);
$pdf->ContentCell(47, 10, $sanitizedNote['week_ending'], 1, 0, 'L');
$pdf->ColoredCell(48, 10, 'Day:', 1, 0, 'L', false);
$pdf->ContentCell(48, 10, $sanitizedNote['day'], 1, 1, 'L');

$pdf->ColoredCell(47, 10, 'Date:', 1, 0, 'L', false);
$pdf->ContentCell(47, 10, $sanitizedNote['date'], 1, 0, 'L');
$pdf->ColoredCell(48, 10, 'Period:', 1, 0, 'L', false);
$pdf->ContentCell(48, 10, $sanitizedNote['period'], 1, 1, 'L');

$pdf->Ln(10);

// --- CURRICULUM DETAILS ---
$pdf->SectionTitle('Curriculum Details');
$pdf->ColoredCell(95, 10, 'Strand:', 1, 0, 'L', false);
$pdf->ContentCell(95, 10, $sanitizedNote['strand'], 1, 1, 'L');
$pdf->ColoredCell(95, 10, 'Sub-Strand:', 1, 0, 'L', false);
$pdf->ContentCell(95, 10, $sanitizedNote['sub_strand'], 1, 1, 'L');
$pdf->ColoredCell(95, 10, 'Indicator (Code):', 1, 0, 'L', false);
$pdf->ContentCell(95, 10, $sanitizedNote['indicator_code'], 1, 1, 'L');
$pdf->ColoredCell(95, 10, 'Content Standard (Code):', 1, 0, 'L', false);
$pdf->ContentCell(95, 10, $sanitizedNote['content_standard_code'], 1, 1, 'L');

$pdf->Ln(8);

// --- PERFORMANCE INDICATOR AND CORE COMPETENCIES ---
$pdf->SetFont('Arial','B',11);
$pdf->MultiCell(0, 8, "Performance Indicator:", 1, 'L');
$pdf->SetFont('Arial','',11);
$pdf->SafeMultiCell(0, 8, $sanitizedNote['performance_indicator'], 1, 'L');
$pdf->Ln(4);

$pdf->SetFont('Arial','B',11);
$pdf->MultiCell(0, 8, "Core Competencies:", 1, 'L');
$pdf->SetFont('Arial','',11);
$pdf->SafeMultiCell(0, 8, $sanitizedNote['core_competencies'], 1, 'L');
$pdf->Ln(8);

// --- RESOURCES ---
$pdf->SectionTitle('Teaching Resources');
$pdf->ColoredCell(140, 10, 'Teaching/Learning Resources:', 1, 0, 'L', false);
$pdf->ContentCell(65, 10, $sanitizedNote['tls'], 1, 1, 'L');
$pdf->ColoredCell(140, 10, 'References:', 1, 0, 'L', false);
$pdf->ContentCell(65, 10, $sanitizedNote['ref'], 1, 1, 'L');

$pdf->Ln(9);

// --- LESSON PHASES ---
$pdf->SectionTitle('Lesson Phases');
for ($i = 1; $i <= 3; $i++) {
    $phaseContent = $sanitizedNote['phase'.$i] ?? 'No content available';
    $pdf->PhaseBox($i, $phaseContent);
}

// --- APPROVAL ---
$pdf->SetY(-35);
$pdf->SetFont('Arial', 'I', 12);
$pdf->SetTextColor($pdf->getDarkColor()[0], $pdf->getDarkColor()[1], $pdf->getDarkColor()[2]);
$pdf->Cell(0, 10, 'Vetted by: ....................................................', 0, 1, 'R');
$pdf->SetFont('Arial', '', 10);
$pdf->SetTextColor($pdf->getMutedColor()[0], $pdf->getMutedColor()[1], $pdf->getMutedColor()[2]);
$pdf->Cell(0, 5, 'Signature & Date', 0, 1, 'R');

// --- OUTPUT ---
$filename = 'professional_lesson_plan_' . $note_id . '_' . date('Y-m-d') . '.pdf';
$preview = isset($_GET['preview']) && $_GET['preview'] == 1;

header('Content-Type: application/pdf');
header('Cache-Control: private, must-revalidate, post-check=0, pre-check=0, max-age=1');

if ($preview) {
    // Inline preview in browser
    header('Content-Disposition: inline; filename="' . $filename . '"');
    $pdf->Output('I', $filename);
} else {
    // Force download
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Transfer-Encoding: binary');
    header('Accept-Ranges: bytes');
    $pdf->Output('D', $filename);
}

exit;
?>
